### PR TITLE
WIP Add github action for building doc

### LINKED ISSUE #7: Use github actions?
Should we use github actions to render the sample project? It would have the benefit to be very easy to set up by end users.

### PR DESCRIPTION
**Pull request by lucyleeow**
closes #7

### CODE REVIEW

**Comment by larsoner** [comment]
I have not seen a way to make actions take effect in the PR that adds them. Probably worth looking into if you want to test this. Otherwise you'll be stuck actually pushing a branch to this repo (rather than your own) which is annoying.

Actually I guess you could just look here:

https://github.com/lucyleeow/sample-project/actions

I'd recommend [enabling Actions debug mode on your repo, too](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging)

**Comment by lucyleeow** [comment]
@larsoner I wasn't sure how best to name the github action workflow .yml file. I called it `sphinx_build.yml` - is this reasonable?

I used the community workflows [sphinx build action](https://github.com/ammaraskar/sphinx-action) and [upload artifacts](https://github.com/actions/upload-artifact) - reasonable?

Otherwise good to go.

**Comment by larsoner** [comment]
> I used the community workflows sphinx build action and upload artifacts - reasonable?

I would use whatever is most common + easy + supported, sounds like these probably are

One thing that is missing is some sort of status update, is there a GitHub action to make a link to one of the artifacts that is produced by the `upload artifacts` step (e.g., the `index.html`)? If not it might be worth building a simple one. See for example the action I wrote (which is more complicated) to monitor CircleCI status badges and make a GitHub status link to their artifacts:

https://github.com/larsoner/circleci-artifacts-redirector-action

**Comment by lucyleeow** [comment]
I don't think there is a way to do that: https://github.community/t5/GitHub-Actions/Link-to-latest-artifacts/td-p/36394

Further you can only download the artifact, and cannot get a link to view the html pages directly. And there does not even seem to be a way to get a link to download the uploaded artifact -  https://github.com/actions/upload-artifact/issues/27

**Comment by larsoner** [comment]
These seem like pretty bad deficiencies compared to CircleCI to the point where I would not recommend people use GitHub actions...

**Comment by lucyleeow** [comment]
I agree. Maybe we can table this until this feature is added? @GaelVaroquaux feel free to pitch in.

**Comment by larsoner** [comment]
FYI I'm fine with merging this as is, too, so long as we add some comment noting the limitations we've hit. It's still useful to have as a template in case people don't care about the limitation, or if at some point we figure out how to get around it.

**Comment by lucyleeow** [comment]
I don't mind either way. I'm working on some documentation in `README.md` atm so can discuss this there. I guess CircleCI is a bit tricker to set up at the start...

**Comment by lucyleeow** [comment]
Merging this and noting limitations in readme

**Comment by choldgraf** [comment]
wait @larsoner didn't you build a github actions bot just to do this very thing?

**Comment by larsoner** [comment]
For CircleCI artifacts yes, not for GitHub actions artifacts

**Comment by choldgraf** [comment]
Ohhh I see - I thought that https://github.com/larsoner/circleci-artifacts-redirector-action was doing this, but I guess that's just an action to look at the CircleCI artifacts, not to point to GHA artifacts

**Pull request merged**
